---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/bebppfmy/public_html
    - export STATIC=/home4/bebppfmy/public_html/static
    - /bin/cp static/* $STATIC
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp index.txt $DEPLOYPATH
