on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: beb.ppf.mybluehost.me
        username: ${{ secrets.BLUEHOST_USERNAME }}
        password: ${{ secrets.BLUEHOST_PASSWORD }}
        server-dir: /public_html/